services:
  web:
    build:
      context: ./
      dockerfile: ./recipe_site/Dockerfile
    volumes:
      - ./recipe_site:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=recipe_site.settings
    command: python manage.py runserver 0.0.0.0:8000

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - ./var/www/certbot:/var/www/certbot  # Убедитесь, что путь правильный
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./var/www/certbot:/var/www/certbot  # Обновите путь
    command: certonly --webroot --webroot-path=/var/www/certbot --email kochenof@yandex.ru --agree-tos --no-eff-email -d kochenov.ru -d www.kochenov.ru
